baseURL = "https://freelanguagetools.org/"
languageCode = "en-us"
title = "FreeLanguageTools"
theme = "fuji"
[params]
Subtitle = "Immerse in languages with your freedoms intact"
SourceURL = "https://github.com/FreeLanguageTools/freelanguagetools.org"
showLicenseInFooter = true
license = "CC BY-SA 4.0"
licenseLink = "https://creativecommons.org/licenses/by-sa/4.0/"

[permalinks]
posts = '/:year/:month/:title/'

[menu]
[[menu.link]]
name = "Join us on Matrix"
URL = "https://matrix.to/#/#flt:midov.pl"
[[menu.link]]
name = "Latest release of ssmtool"
URL = "https://github.com/FreeLanguageTools/ssmtool/releases"
