baseURL = "https://freelanguagetools.org/"
languageCode = "en-us"
title = "FreeLanguageTools"
theme = "fuji"
[params]
Subtitle = "Immerse in languages with your freedoms intact"
SourceURL = "https://github.com/FreeLanguageTools/freelanguagetools.org"
showLicenseInFooter = true
license = "CC BY-SA 4.0"
licenseLink = "https://creativecommons.org/licenses/by-sa/4.0/"

[permalinks]
posts = '/:year/:month/:title/'

[menu]
[[menu.link]]
name = "Talk to us on Matrix"
URL = "https://webchat.kde.org/#/room/#flt:midov.pl"
[[menu.link]]
name = "Talk to us on Telegram"
URL = "https://t.me/fltchat"
[[menu.link]]
name = "Latest release of SSM"
URL = "https://github.com/FreeLanguageTools/ssmtool/releases"
[[menu.link]]
name = "Web reader for SSM"
URL = "/apps/reader"
[[menu.link]]
name = "Text vocabulary analyzer"
URL = "/apps/rangescore"
